spring:
  application:
    name: greeting-service
#agora vamos liberar endpoints, para testes e saber sobre os endpoints 
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "Olá! Tudo bem?"
  default-value: "Fernando você é legal..."
